version: '2.2'
services:
  rabbit:
    image: "rabbitmq"
    expose:
      - "5672"
  rabbit-consumer:
    build:
      context: rabbit-consumer
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - rabbit
  flask-app:
    build:
      context: flask-app
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - rabbit
      - storage
  storage:
    image: postgres:11.2-alpine
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=app_storage
